# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"-\n\x16\x43hatInformationRequest\x12\x13\n\x0b\x63hannelName\x18\x01 \x01(\t\"!\n\x10UserCountMessage\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"B\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12 \n\x06status\x18\x03 \x01(\x0e\x32\x10.chat.UserStatus\",\n\x0fUserListMessage\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.chat.User\"8\n\x0b\x43hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.chat.User*/\n\nUserStatus\x12\n\n\x06ONLINE\x10\x00\x12\x0b\n\x07OFFLINE\x10\x01\x12\x08\n\x04\x41WAY\x10\x02\x32\xe0\x01\n\x04\x43hat\x12H\n\x0cGetUserCount\x12\x1c.chat.ChatInformationRequest\x1a\x16.chat.UserCountMessage\"\x00\x30\x01\x12\x46\n\x0bGetUserList\x12\x1c.chat.ChatInformationRequest\x1a\x15.chat.UserListMessage\"\x00\x30\x01\x12\x46\n\x0fGetChatMessages\x12\x1c.chat.ChatInformationRequest\x1a\x11.chat.ChatMessage\"\x00\x30\x01\x42*\n\x15io.grpc.examples.chatB\tChatProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.examples.chatB\tChatProtoP\001\242\002\003HLW'
  _USERSTATUS._serialized_start=274
  _USERSTATUS._serialized_end=321
  _CHATINFORMATIONREQUEST._serialized_start=20
  _CHATINFORMATIONREQUEST._serialized_end=65
  _USERCOUNTMESSAGE._serialized_start=67
  _USERCOUNTMESSAGE._serialized_end=100
  _USER._serialized_start=102
  _USER._serialized_end=168
  _USERLISTMESSAGE._serialized_start=170
  _USERLISTMESSAGE._serialized_end=214
  _CHATMESSAGE._serialized_start=216
  _CHATMESSAGE._serialized_end=272
  _CHAT._serialized_start=324
  _CHAT._serialized_end=548
# @@protoc_insertion_point(module_scope)
