# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserCount = channel.unary_stream(
                '/chat.Chat/GetUserCount',
                request_serializer=chat__pb2.ChatInformationRequest.SerializeToString,
                response_deserializer=chat__pb2.UserCountMessage.FromString,
                )
        self.GetUserList = channel.unary_stream(
                '/chat.Chat/GetUserList',
                request_serializer=chat__pb2.ChatInformationRequest.SerializeToString,
                response_deserializer=chat__pb2.UserListMessage.FromString,
                )
        self.GetChatMessages = channel.unary_stream(
                '/chat.Chat/GetChatMessages',
                request_serializer=chat__pb2.ChatInformationRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatMessage.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserCount': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserCount,
                    request_deserializer=chat__pb2.ChatInformationRequest.FromString,
                    response_serializer=chat__pb2.UserCountMessage.SerializeToString,
            ),
            'GetUserList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUserList,
                    request_deserializer=chat__pb2.ChatInformationRequest.FromString,
                    response_serializer=chat__pb2.UserListMessage.SerializeToString,
            ),
            'GetChatMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChatMessages,
                    request_deserializer=chat__pb2.ChatInformationRequest.FromString,
                    response_serializer=chat__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.Chat/GetUserCount',
            chat__pb2.ChatInformationRequest.SerializeToString,
            chat__pb2.UserCountMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.Chat/GetUserList',
            chat__pb2.ChatInformationRequest.SerializeToString,
            chat__pb2.UserListMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChatMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.Chat/GetChatMessages',
            chat__pb2.ChatInformationRequest.SerializeToString,
            chat__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
